// <auto-generated />
using ExamensArbete_BA_WIN23.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ExamensArbete_BA_WIN23.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamensArbete_BA_WIN23.API.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("isDeactivated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ExamensArbete_BA_WIN23.Business.Entities.ChangeRequest", b =>
                {
                    b.Property<Guid>("ChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Customer")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DateSentBV")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FirstApprover")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<Guid?>("SecondApprover")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("isSignCompleted")
                        .HasColumnType("bit");

                    b.HasKey("ChangeRequestId");

                    b.ToTable("ChangeRequests");
                });

            modelBuilder.Entity("ExamensArbete_BA_WIN23.API.Entities.Notification", b =>
                {
                    b.HasOne("ExamensArbete_BA_WIN23.Business.Entities.ChangeRequest", "ChangeRequest")
                        .WithMany()
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
